package com.example.emptySaver.utils;

import com.example.emptySaver.domain.entity.Subject;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class UosSubjectAutoSaverTest {
    @Autowired
    private UosSubjectAutoSaver uosSubjectAutoSaver;

    @Test
    void Html파싱테스트(){
        String data = "<?xml version=\"1.0\" encoding=\"EUC-KR\"?>\n" +
                "<root xmlns=\"\">\n" +
                "<mainlist>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[38163]]></subject_no>\n" +
                "<class_div><![CDATA[04]]></class_div>\n" +
                "<subject_nm><![CDATA[공과대학현장실습Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[이병정]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>2</tlsn_limit_count>\n" +
                "<tlsn_count>2</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71006]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[객체지향프로그래밍및실습]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월02,03/19-110/111, 목05,06/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[이병정]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>35</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71006]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[객체지향프로그래밍및실습]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월05,06/19-110/111, 목05,06/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[이병정]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>40</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71007]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[선형대수]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월07,08,09/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[김민호]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>65</tlsn_limit_count>\n" +
                "<tlsn_count>68</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71008]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[이산수학]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[수06,07,08/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[정형구]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>39</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71008]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[이산수학]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목07,08,09/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[정형구]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>40</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71013]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[화일처리론]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월10,11,12/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[노창배]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>65</tlsn_limit_count>\n" +
                "<tlsn_count>29</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71015]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[운영체제]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목07,08,09/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[현철승]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>70</tlsn_limit_count>\n" +
                "<tlsn_count>70</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71018]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴파일러구성]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목02,03,04/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[안상현]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>53</tlsn_limit_count>\n" +
                "<tlsn_count>48</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71021]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터통신]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화03,04/19-110/111, 금03/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[안상현]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>65</tlsn_limit_count>\n" +
                "<tlsn_count>64</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71028]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터보안]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[수01,02,03/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[최혁]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>65</tlsn_limit_count>\n" +
                "<tlsn_count>47</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71039]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터알고리즘]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월07,08,09/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[김진석]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>30</tlsn_limit_count>\n" +
                "<tlsn_count>26</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71042]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[확률과통계]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목02,03,04/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[유하진]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>65</tlsn_limit_count>\n" +
                "<tlsn_count>67</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71048]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[데이터베이스설계]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화05,06,07/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[홍의경]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>24</tlsn_limit_count>\n" +
                "<tlsn_count>18</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71055]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[멀티미디어응용]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화02,03,04/19-328/329]]></class_nm>\n" +
                "<prof_nm><![CDATA[김성환]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>9</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71066]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[웹정보시스템]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월02,03/19-112/113, 화02/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[황혜수]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>16</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71068]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[윈도우즈프로그래밍]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월04,05,06/19-326/327]]></class_nm>\n" +
                "<prof_nm><![CDATA[현철승]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>48</tlsn_limit_count>\n" +
                "<tlsn_count>44</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[안상현]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>6</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[김진석]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[03]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[유하진]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[04]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[김성환]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>7</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[05]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[이병정]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[06]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[최혁]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[07]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[김민호]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>7</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[08]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[황혜수]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71071]]></subject_no>\n" +
                "<class_div><![CDATA[09]]></class_div>\n" +
                "<subject_nm><![CDATA[학업설계상담 Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>0</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[정형구]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>10</tlsn_limit_count>\n" +
                "<tlsn_count>8</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71077]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터과학종합설계]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[금01,02,03,04/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[최혁]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>20</tlsn_limit_count>\n" +
                "<tlsn_count>17</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71077]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터과학종합설계]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[수06,07,08,09/19-328/329]]></class_nm>\n" +
                "<prof_nm><![CDATA[김진석]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>20</tlsn_limit_count>\n" +
                "<tlsn_count>10</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71078]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[논리회로및실습]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화05,06/19-110/111, 금01,02/19-326/327]]></class_nm>\n" +
                "<prof_nm><![CDATA[김민호]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>35</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공필수]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공필수]]></subject_div>\n" +
                "<subject_no><![CDATA[71078]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[논리회로및실습]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>2</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화08,09/19-326/327, 금06,07/19-326/327]]></class_nm>\n" +
                "<prof_nm><![CDATA[김민호]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>40</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71079]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터구조론 ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[수09,10,11/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[송영록]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>50</tlsn_limit_count>\n" +
                "<tlsn_count>44</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71080]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[프로그래밍입문]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목05/19-112/113, 금06,07/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[김성환]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>35</tlsn_limit_count>\n" +
                "<tlsn_count>10</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71089]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[멀티프로세서컴퓨팅]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>4</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[목10,11,12/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[노창배]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>40</tlsn_limit_count>\n" +
                "<tlsn_count>28</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71095]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터과학개론]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[월05/19-112/113, 수03,04/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[황혜수]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>35</tlsn_limit_count>\n" +
                "<tlsn_count>39</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71095]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터과학개론]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>1</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[화03/19-112/113, 수06,07/19-112/113]]></class_nm>\n" +
                "<prof_nm><![CDATA[황혜수]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>35</tlsn_limit_count>\n" +
                "<tlsn_count>26</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71081]]></subject_no>\n" +
                "<class_div><![CDATA[01]]></class_div>\n" +
                "<subject_nm><![CDATA[연구인턴십Ⅰ]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[]]></class_nm>\n" +
                "<prof_nm><![CDATA[이병정]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>1</tlsn_limit_count>\n" +
                "<tlsn_count>1</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[N]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[N]]></sec_permit_yn>\n" +
                "</list>\n" +
                "<list>\n" +
                "<year><![CDATA[2023]]></year>\n" +
                "<term><![CDATA[A10]]></term>\n" +
                "<subject_div2><![CDATA[전공선택]]></subject_div2>\n" +
                "<subject_div><![CDATA[전공선택]]></subject_div>\n" +
                "<subject_no><![CDATA[71039]]></subject_no>\n" +
                "<class_div><![CDATA[02]]></class_div>\n" +
                "<subject_nm><![CDATA[컴퓨터알고리즘]]></subject_nm>\n" +
                "<sub_dept><![CDATA[컴퓨터과학부]]></sub_dept>\n" +
                "<day_night_nm><![CDATA[주간]]></day_night_nm>\n" +
                "<shyr>3</shyr>\n" +
                "<credit>3</credit>\n" +
                "<class_nm><![CDATA[금06,07,08/19-110/111]]></class_nm>\n" +
                "<prof_nm><![CDATA[김진석]]></prof_nm>\n" +
                "<class_type><![CDATA[]]></class_type>\n" +
                "<tlsn_limit_count>30</tlsn_limit_count>\n" +
                "<tlsn_count>9</tlsn_count>\n" +
                "<etc_permit_yn><![CDATA[Y]]></etc_permit_yn>\n" +
                "<sec_permit_yn><![CDATA[Y]]></sec_permit_yn>\n" +
                "</list>\n" +
                "</mainlist>\n" +
                "<_COLUMNS_OF_TABLE_TO_TEXT_>{}</_COLUMNS_OF_TABLE_TO_TEXT_>\n" +
                "</root>\n" +
                "\n";

        List<Subject> subjects = uosSubjectAutoSaver.parseSubjectsHtmlData(data);
        for (Subject sub: subjects) {
            System.out.println(sub.getClass_nm());
            for (long l:sub.getWeekScheduleData()) {
                System.out.println(Long.toBinaryString(l));
            }
        }
    }
}